import { NextResponse } from "next/server";

import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";

// POST /api/admin/create-pharmacy — admin only (session + is_admin gated).
// Creates the owner auth user and the pharmacy row (license_key auto-generated),
// compensating by deleting the user if the pharmacy insert fails.
export async function POST(request: Request) {
  try {
    // Verify the caller is an admin via their session.
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user || user.user_metadata?.is_admin !== true) {
      return NextResponse.json({ error: "Accès refusé" }, { status: 403 });
    }

    let body: { name?: unknown; email?: unknown; password?: unknown };
    try {
      body = await request.json();
    } catch {
      return NextResponse.json({ error: "Requête invalide" }, { status: 400 });
    }

    const { name, email, password } = body;
    if (
      typeof name !== "string" ||
      typeof email !== "string" ||
      typeof password !== "string" ||
      !name.trim() ||
      !email.trim() ||
      !password
    ) {
      return NextResponse.json(
        { error: "Champs requis manquants" },
        { status: 400 },
      );
    }

    const admin = createAdminClient();

    // 1. Create the owner auth user (email pre-confirmed — no email flow).
    const { data: created, error: createError } =
      await admin.auth.admin.createUser({
        email,
        password,
        email_confirm: true,
      });
    if (createError || !created?.user) {
      return NextResponse.json(
        { error: createError?.message ?? "Échec de création de l'utilisateur" },
        { status: 400 },
      );
    }

    // 2. Insert the pharmacy; license_key is auto-generated by the DB default.
    const { data: pharmacy, error: insertError } = await admin
      .from("pharmacies")
      .insert({ name: name.trim(), owner_id: created.user.id })
      .select("id, license_key")
      .single();

    if (insertError || !pharmacy) {
      // Compensate: remove the orphaned auth user so accounts don't leak.
      await admin.auth.admin.deleteUser(created.user.id);
      return NextResponse.json(
        {
          error:
            insertError?.message ?? "Échec de création de la pharmacie",
        },
        { status: 400 },
      );
    }

    return NextResponse.json(
      {
        pharmacy_id: pharmacy.id,
        license_key: pharmacy.license_key,
        owner_email: email,
      },
      { status: 201 },
    );
  } catch (error) {
    console.error("[/api/admin/create-pharmacy] error:", error);
    return NextResponse.json({ error: "Erreur serveur" }, { status: 500 });
  }
}
